import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import AppShell from '../components/AppShell'
import { ErrorState } from '../components/PageState'
import { createCharacter, getCharacter, updateCharacter } from '../api/characters'

const fields = [
  ['name', 'Name', true], ['surname', 'Surname'], ['sex', 'Sex'], ['age', 'Age'],
  ['height_or_size', 'Height / Size'], ['hair_color', 'Hair Color'], ['eye_color', 'Eye Color'],
  ['clothing_style', 'Clothing Style'], ['accessories', 'Accessories'], ['personality', 'Personality'],
  ['clothing', 'Clothing'], ['history', 'History'], ['importance', 'Importance'],
]

export default function CharacterFormPage() {
  const { id: projectId, characterId } = useParams(); const editing = Boolean(characterId); const navigate = useNavigate()
  const [form, setForm] = useState({ name: '', surname: '', sex: '', age: '', height_or_size: '', hair_color: '', eye_color: '', clothing_style: '', accessories: '', personality: '', clothing: '', history: '', importance: '', reference_image: null })
  const [state, setState] = useState({ loading: editing, saving: false, error: '' })
  useEffect(() => { if (editing) getCharacter(characterId).then((response) => setForm((current) => ({ ...current, ...response.data }))).catch(() => setState({ loading: false, saving: false, error: 'Unable to load character.' })).finally(() => setState((current) => ({ ...current, loading: false }))) }, [editing, characterId])
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.type === 'file' ? event.target.files[0] : event.target.value })
  const submit = async (event) => { event.preventDefault(); setState({ ...state, saving: true, error: '' }); const payload = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value !== null && value !== '') payload.append(key, value) }); try { const response = editing ? await updateCharacter(characterId, payload) : await createCharacter(projectId, payload); navigate(`/projects/${projectId}`) } catch (error) { setState({ ...state, saving: false, error: Object.values(error.response?.data || {}).flat().join(' ') || 'Unable to save character.' }) } }
  if (state.loading) return <AppShell><p className="py-16 text-slate-400">Loading...</p></AppShell>
  const field = ([name, label, required]) => <label key={name} className="block"><span className="studio-label">{label}{required && <span className="ml-1 text-amber-300">*</span>}</span>{['accessories', 'personality', 'clothing', 'history'].includes(name) ? <textarea required={required} name={name} value={form[name] || ''} onChange={update} rows="3" className="studio-input resize-y" /> : <input required={required} type={name === 'age' ? 'number' : 'text'} name={name} value={form[name] || ''} onChange={update} className="studio-input" />}</label>
  return <AppShell><section className="mx-auto max-w-4xl py-10"><Link to={`/projects/${projectId}`} className="text-sm text-slate-500 hover:text-violet-300">← Back to project</Link><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[0.22em] text-violet-300">Character management</p><h1 className="mt-2 text-3xl font-bold text-white md:text-4xl">{editing ? 'Edit character' : 'Create Character'}</h1><p className="mt-3 text-sm text-slate-400">Build a consistent reference for the people in your story.</p></div>{state.error && <div className="mt-6"><ErrorState message={state.error} /></div>}<form onSubmit={submit} className="mt-8 space-y-5"><section className="studio-card p-6 md:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-300">01 / Identity</p><h2 className="mt-2 text-xl font-bold text-white">Basic information</h2></div><div className="grid gap-5 md:grid-cols-2">{fields.slice(0, 5).map(field)}</div></section><section className="studio-card p-6 md:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-300">02 / Visual language</p><h2 className="mt-2 text-xl font-bold text-white">Appearance</h2></div><div className="grid gap-5 md:grid-cols-2">{fields.slice(5, 8).map(field)}<label className="block md:col-span-2"><span className="studio-label">Accessories</span><textarea name="accessories" value={form.accessories || ''} onChange={update} rows="3" className="studio-input resize-y" /></label><label className="block md:col-span-2"><span className="studio-label">Reference image</span><span className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-white/[0.15] bg-black/10 px-4 text-center text-sm text-slate-400 hover:border-violet-400/50"><span className="mb-2 text-2xl text-violet-300">＋</span>{form.reference_image?.name || 'Drop an image here or browse'}<input type="file" accept="image/*" name="reference_image" onChange={update} className="hidden" /></span></label></div></section><section className="studio-card p-6 md:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-300">03 / Story layer</p><h2 className="mt-2 text-xl font-bold text-white">Personality & history</h2></div><div className="grid gap-5 md:grid-cols-2">{fields.slice(9).map(field)}</div></section><div className="flex flex-wrap justify-end gap-3"><Link to={`/projects/${projectId}`} className="secondary-button">Cancel</Link><button disabled={state.saving} className="primary-button">{state.saving ? 'Saving...' : editing ? 'Save changes' : 'Create Character'}</button></div></form></section></AppShell>
}
