import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import AppShell from '../components/AppShell'
import { EmptyState, LoadingState } from '../components/PageState'
import ProjectCard from '../components/ProjectCard'
import { listProjects } from '../api/projects'
import { listAllCharacters } from '../api/characters'
import { useAuth } from '../context/AuthContext'

export default function DashboardPage() {
  const { user } = useAuth(); const [projects, setProjects] = useState([]); const [characterCount, setCharacterCount] = useState(0); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([listProjects(), listAllCharacters()]).then(([projectResponse, characterResponse]) => { setProjects(projectResponse.data.slice(0, 3)); setCharacterCount(characterResponse.data.length) }).finally(() => setLoading(false)) }, [])
  return <AppShell><section className="py-10"><div className="studio-card relative overflow-hidden p-7 md:p-10"><div className="pointer-events-none absolute right-[-5%] top-[-60%] h-[380px] w-[380px] rounded-full border-[48px] border-violet-400/[0.06]" /><div className="relative max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-violet-300">Creator workspace</p><h2 className="mt-3 text-3xl font-bold text-white md:text-5xl">Welcome back, {user?.name?.split(' ')[0]}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-slate-400">Shape your next manga world, keep your cast consistent, and move from first idea to finished story.</p><Link to="/projects/new" className="primary-button mt-7">＋ Create New Project</Link></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total Projects', projects.length, '▦'], ['Total Characters', characterCount, '✦'], ['Total Episodes', '—', '▶'], ['Credits Remaining', '—', '◈']].map(([label, value, icon]) => <div key={label} className="studio-card flex items-center justify-between p-5"><div><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><strong className="mt-2 block text-2xl text-white">{value}</strong></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-400/10 text-violet-300">{icon}</span></div>)}</div><div className="mt-12 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-300">Workspace pulse</p><h2 className="mt-2 text-2xl font-bold text-white">Recent Projects</h2></div><Link to="/projects" className="text-sm font-semibold text-violet-300 hover:text-violet-200">View all →</Link></div>{loading ? <div className="mt-5"><LoadingState /></div> : projects.length ? <div className="mt-5 grid gap-5 lg:grid-cols-3">{projects.map((project) => <ProjectCard key={project.id} project={project} onDelete={() => {}} />)}</div> : <div className="mt-5"><EmptyState message="No projects yet. Your first story world starts here." /></div>}<div className="mt-10 grid gap-5 md:grid-cols-2"><Link to="/projects/new" className="studio-card group p-5 hover:border-amber-300/30"><p className="text-xs uppercase tracking-[0.18em] text-amber-300">Quick action</p><h3 className="mt-3 text-lg font-bold text-white">Create a new project <span className="float-right text-amber-300 transition group-hover:translate-x-1">→</span></h3><p className="mt-2 text-sm text-slate-400">Start with a title, mood, and the seed of a world.</p></Link><Link to="/characters" className="studio-card group p-5 hover:border-violet-300/30"><p className="text-xs uppercase tracking-[0.18em] text-violet-300">Quick action</p><h3 className="mt-3 text-lg font-bold text-white">Build your cast <span className="float-right text-violet-300 transition group-hover:translate-x-1">→</span></h3><p className="mt-2 text-sm text-slate-400">Open a project and give its characters a place to begin.</p></Link></div></section></AppShell>
}
