# Generated by Django 5.2.17 on 2026-09-04 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_or_size', models.CharField(blank=True, max_length=100)),
                ('hair_color', models.CharField(blank=True, max_length=100)),
                ('eye_color', models.CharField(blank=True, max_length=100)),
                ('clothing_style', models.CharField(blank=True, max_length=200)),
                ('accessories', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('clothing', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('importance', models.CharField(blank=True, max_length=50)),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='character_references/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', 'is_deleted'], name='characters__project_2a4dd2_idx'), models.Index(fields=['name', 'is_deleted'], name='characters__name_2888fb_idx')],
            },
        ),
    ]
